### PR TITLE
filter scene by air loop

### LINKED ISSUE #413: Geometry preview - air loops
Enhancement Request
--------------

The main idea is to implement following use cases in 3D geometry preview:
- find by visual inspection thermal zones that have no air loop associated
- inspect thermal zone / air loop associations to ensure correctness (i.e. AHU dedicated to zones with a specific orientation)  

For now only the first use case can be fulfilled with UI by looking into thermal zones tab in OpenStudioApp and scrolling to find those without an air loop. I often revert back to scripting to perform these checks, but I believe 3D view is a good fit for this too.

## Possible Implementation

Since a thermal zone can be associated with [0..n] air loops, there is a slight difference with other materials implementation:
- air loops information in user data will be of array-like type
- when 'air loop' is selected in 'render by' drop-down, a new drop-down menu could be displayed to select a specific air loop (avoid showing all air loops at once, doesn't make sense if zones are associated with 2 air loops or more).
- this new drop-down menu would have a 'no air loop' entry, to highlight material without any air loop associated.

Dependencies:
- it would require a change in OpenStudio too, mainly in `ThreeJSForwardTranslator` to update user data and ThreeJS materials meta data. A change in `ThreeJS` is also needed to declare the new structures that will hold air loops information.

### PR DESCRIPTION
**Pull request by antoine-galataud**
Fixes #413

### CODE REVIEW

**Comment by antoine-galataud** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by antoine-galataud** [comment]
recheck

**Comment by macumber** [comment]
Thanks @antoine-galataud!  I think I fixed the CLA workflow so it will work now:
https://github.com/openstudiocoalition/OpenStudioApplication/commit/3c27e3599d11d797f841dcd6fac548eace964cbc

Could you try fetching and merging the most recent openstudiocoalition/OpenStudioApplication develop branch into your PR and then adding a comment to sign or recheck the CLA again?

**Comment by macumber** [comment]
BTW, this will be a really cool new feature, thanks!

**Comment by antoine-galataud** [comment]
> Could you try fetching and merging the most recent openstudiocoalition/OpenStudioApplication develop branch into your PR and then adding a comment to sign or recheck the CLA again?

@macumber I just merged develop into my PR and the CLA action passed. Do you still want me to re-invoke it with a comment?

**Comment by macumber** [comment]
Nope that looks good!  I just fixed another issue on develop and pushed the button to update your branch, hopefully all the checks will pass now.

**Comment by jmarrec** [comment]
Tested locally, worked fine.

**Pull request merged**
