### PR TITLE
Fix  #345 - Missing libs in Ubuntu installer

### LINKED ISSUE #345: libopenstudiolib.so missing on Ubuntu 18.04 and 20.04 in 1.2.0-rc1 and 1.2.0-rc2
Issue overview
--------------

libopenstudiolib.so isn't installed anymore, it was in 1.1.0.

## Current Behavior

```
(py39)julien@Downloads$ ls /usr/local/openstudioapplication-1.1.0/bin/libopen*
/usr/local/openstudioapplication-1.1.0/bin/libopenstudiolib.so

(py39)julien@Downloads$ ls /usr/local/openstudioapplication-1.2.0-alpha/bin/libopen*
ls: cannot access '/usr/local/openstudioapplication-1.2.0-alpha/bin/libopen*': No such file or directory
```

### PR DESCRIPTION
**Pull request by jmarrec**
Minimal fix #345 : Put back the fixup_bundle call on linux

### CODE REVIEW

**Comment by macumber** [comment]
I installed OpenStudioApplication-1.2.0.747503b71d9842aefb979baf4ab70ca36297228b-ubuntu-20.04.deb from:

https://github.com/openstudiocoalition/OpenStudioApplication/pull/346/checks?check_run_id=2684490329

After installing:
```
macumber@test-ubuntu-2004:~$ ls -alsh /usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa*
   0 lrwxrwxrwx 1 root root   15 May 27 06:20 /usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa -> libQt5XcbQpa.so
1.8M -rwxr-xr-x 1 root root 1.8M May 27 06:20 /usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so
```

```
macumber@test-ubuntu-2004:~$ OpenStudioApp
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

This allowed the app to launch:
```
macumber@test-ubuntu-2004:~$ sudo cp /usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so /usr/local/openstudioapplication-1.2.0-alpha/bin/libQt5XcbQpa.so.5
```

image

**Comment by macumber** [comment]
It's possible that `fixup_bundle` is following symlinks back to `libQt5XcbQpa.so`?  Maybe instead we could have a post install script to create the `libQt5XcbQpa.so.5` and `libQt5XcbQpa.so.5.15.0` symlinks?

**Comment by macumber** [comment]
@jmarrec I think that the build cache might be screwing us here.  The cache is stuck on the old `libQt5XcbQpa.so`.  Is there a way to remotely delete that cache?

**Comment by jmarrec** [comment]
> It's possible that `fixup_bundle` is following symlinks back to `libQt5XcbQpa.so`? Maybe instead we could have a post install script to create the `libQt5XcbQpa.so.5` and `libQt5XcbQpa.so.5.15.0` symlinks?

We actually have a cmake script thzt does the reverse currently.

**Comment by jmarrec** [comment]
Dan, don't bother with this branch. I have one commit on the 1.2.0rc2 thzt would fix it https://github.com/openstudiocoalition/OpenStudioApplication/commit/bce64630cd409ace96f453d3a74f4e9a8696aabb

**Pull request merged**
