### PR TITLE
Completed TS file for Spanish

### PR DESCRIPTION
**Pull request by luisclv**
I am committing both the TS and QM files. I did all the sections.

I did not build OS, but I will give it a try this weekend with your instructions.

EDIT:

There are multiple strings that do not require translation (such as [this](https://github.com/openstudiocoalition/OpenStudioApplication/blob/23be211ededa7c0e48119bbce05ebdc249cd7b89/translations/OpenStudioApp_es.ts#L265)). I assumed that if I just typed CTRL+Enter, it would use the original string, but I am not sure. Let me know if I should also copy and paste that type of string and I will fix my PR.

### CODE REVIEW

**Comment by jmarrec** [comment]
Thanks @luisclv ! Yes you do need to copy paste the original string or it'll be blank in the translated one.

**Comment by jmarrec** [comment]
I merged to the Internationalization branch, and cleaning it up. Thanks a lot for your help translating it. I'll be in touch with an installer link for you to test

**Comment by jmarrec** [comment]
image

**Comment by luisclv** [comment]
Thank you for fixing it!

**Pull request merged**
