### PR TITLE
Bump v340rc2

### PR DESCRIPTION
**Pull request by macumber**
Creating a draft PR so @j-lorrey can follow along on the process of a version bump

### CODE REVIEW

**Comment by jmarrec** [comment]
I got it to build, but there problems with the mac bundle related to the Geometry editor (at least on M1 macs). I also updated to Qt 6.3.0 and OpenStudio 3.4.0-rc2

```
dyld[55072]: Library not loaded: @executable_path/../Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore
  Referenced from: /Users/julien/Software/Others/OSApp-build-release/_CPack_Packages/Darwin/TGZ/OpenStudioApplication-1.4.0--rc1+518ddb96cf-macOS12.1-arm64/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: tried: '/Users/julien/Software/Others/OSApp-build-release/_CPack_Packages/Darwin/TGZ/OpenStudioApplication-1.4.0--rc1+518ddb96cf-macOS12.1-arm64/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/../Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file), '/Library/Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file), '/System/Library/Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file)
dyld[55074]: Library not loaded: @executable_path/../Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore
  Referenced from: /Users/julien/Software/Others/OSApp-build-release/_CPack_Packages/Darwin/TGZ/OpenStudioApplication-1.4.0--rc1+518ddb96cf-macOS12.1-arm64/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: tried: '/Users/julien/Software/Others/OSApp-build-release/_CPack_Packages/Darwin/TGZ/OpenStudioApplication-1.4.0--rc1+518ddb96cf-macOS12.1-arm64/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/../Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file), '/Library/Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file), '/System/Library/Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore' (no such file)
```

**Comment by macumber** [comment]
Fixes https://github.com/openstudiocoalition/OpenStudioApplication/issues/505

**Comment by macumber** [comment]
I'm not much help on the M1 stuff until I get ahold of one myself.  Does the file referenced exist?  Is it built with the right architecture?

**Comment by jmarrec** [comment]
@macumber My guess is that the exact same issue happens on non M1 macs. Yes the file exists, it's just the RPATH stuff that's not right.

```
$ otool -l /Users/julien/Qt/6.3.0/macos/lib/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess > ori.txt

$ otool -l /Users/julien/Software/Others/OSApp-build-release/_CPack_Packages/Darwin/TGZ/OpenStudioApplication-1.4.0-rc1+32ca81a498-macOS12.1-arm64/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess > new.txt 
```

image (5)

**Comment by macumber** [comment]
Ok if it’s just a qt change I could look at that

**Comment by macumber** [comment]
I just built this branch on my x86 Mac and did not have this issue.  Did you try building the IFW installer and installing that?  Or were you trying to run the app out of your build dir?

**Comment by macumber** [comment]
This seems to be the magic that is created during the IFW install (I don't know where this happens)

If IFW build directory:
```
mymac@MacBook-Pro-2 Darwin % ls -alsh IFW/OpenStudioApplication-1.3.1+28a7380963-macOS10.15-x86_64/packages/OpenStudioApp/data/OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/     
total 8
0 drwxrwxr-x  5 mymac  staff   160B Apr 30 15:55 .
0 drwxrwxr-x  3 mymac  staff    96B Apr 30 15:55 ..
8 -rw-r--r--  1 mymac  staff   973B Apr  5 17:43 Info.plist
0 drwxrwxr-x  4 mymac  staff   128B Apr 30 15:55 MacOS
0 drwxrwxrwx  3 mymac  staff    96B Apr 30 15:55 Resources
```

In IFW installed directory there is a symlink to the top level Frameworks dir:
```
mymac@MacBook-Pro-2 OpenStudioApplication-1.3.1 % ls -alsh OpenStudioApp.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/A/Helpers/QtWebEngineProcess.app/Contents/
total 8
0 drwxrwxr-x  6 mymac  admin   192B Apr 30 16:21 .
0 drwxrwxr-x  3 mymac  admin    96B Apr 30 16:21 ..
0 lrwxr-xr-x  1 root   admin    31B Apr 30 16:21 Frameworks -> ../../../../../../../Frameworks
8 -rw-r--r--  1 mymac  admin   973B Apr  5 17:43 Info.plist
0 drwxrwxr-x  4 mymac  admin   128B Apr 30 16:21 MacOS
0 drwxrwxrwx  3 mymac  admin    96B Apr 30 16:21 Resources
```

Maybe something in IFW installer goes through and adds symlinks to top level Frameworks dir to all child app dirs?

**Comment by jmarrec** [comment]
yes, that symlink is created here: https://github.com/openstudiocoalition/OpenStudioApplication/blob/7078341fc4628ae5746c093c898fb97901d00b6a/src/openstudio_app/install_operations.qs#L32-L34

The IFW does work on M1 too!

I know the build dir Products/OpenStudioApp doesn't work on mac (and it's probably too annoying to fix). I think I may have been testing the build_dir/_CPack **and** the tar.gz installer, not the IFW one. 

I think we should cmake `install` that symlink instead of having it in the install_operations.qs so that the tar.gz installer works too.

**Comment by jmarrec** [comment]
@macumber I moved the symlink Frameworks for QtWebengine to CMakeLists.txt so that the TGZ installer works. Let's merge this one in.

**Comment by jmarrec** [comment]
@macumber The TGZ still doesn't work, because only the QtIFW does that (which is nuts... we copy so much heavy stuff around): https://github.com/openstudiocoalition/OpenStudioApplication/blob/b92027915b07801e80cd9ccc3d75e0b54df7a533/src/openstudio_app/install_operations.qs#L13-L26

**Comment by macumber** [comment]
Maybe it's best to move https://github.com/openstudiocoalition/OpenStudioApplication/pull/499/commits/db7741bfdab93dd975d10984a3a6fbe7068342f6 to a separate PR for https://github.com/openstudiocoalition/OpenStudioApplication/issues/512 ?

**Comment by jmarrec** [comment]
I moved the commit to the 512_TGZ_mac_installer. I'm merging this one, I need it to review #496

**Comment by macumber** [comment]
Sounds good!

**Pull request merged**
