### PR TITLE
Fixes crash on save when model directory is open in Explorer on Windows

### PR DESCRIPTION
**Pull request by macumber**
Fixes https://github.com/openstudiocoalition/OpenStudioApplication/issues/177

Depends on https://github.com/NREL/OpenStudio/pull/4026

We should decide if we want to fork OpenStudio to get this change in the app earlier, if we want to wait for NREL to make a release with it, or something else

### CODE REVIEW

**Comment by macumber** [comment]
@jmarrec I branched this from your fix clang format commit which I thought was already on develop

**Comment by macumber** [comment]
Closed in favor of https://github.com/openstudiocoalition/OpenStudioApplication/pull/198

**Comment by macumber** [comment]
Re-opened because other PR has clang format issues

**Comment by jmarrec** [comment]
Ran clang format on #198, so use that instead.

**Pull request closed without merging**
