### PR TITLE
Run Clang checks: `performance-for-range-copy` `readability-qualified-auto`, `modernize-use-auto`, `modernize-use-using -fix`

### PR DESCRIPTION
**Pull request by jmarrec**

### CODE REVIEW

**Comment by macumber** [comment]
This all looks good to me, is the performance for range based loops check not smart enough to know when it can't use const?  I saw you had to manually fix that.

**Review by macumber — APPROVED** [review]
Looks good!

**Comment by macumber** [comment]
Merge when you are ready!

**Comment by jmarrec** [comment]
> This all looks good to me, is the performance for range based loops check not smart enough to know when it can't use const?  I saw you had to manually fix that.

It misfires sometimes yes. There are more clang tidy checks that could fix it further though, but I'm trying to do something targeted so not enabling 100 checks and ending up with something impossible to review and even spot check.

**Pull request merged**
